### PR TITLE
Updated CHANGELOG and package.json for release of 1.0.0-pre.3

### PR DESCRIPTION
**Pull request by usergenic**
- [ ] koa-node-resolve@1.0.0-pre.3

Fixed TypeScript typings for logger option.

### CODE REVIEW

**Comment by aomarks** [comment]
LGTM but if possible would be nice to get https://github.com/Polymer/koa-node-resolve/pull/7/files in (just sent for review).

**Comment by usergenic** [comment]
@aomarks Ok checking out #7

**Comment by usergenic** [comment]
Merged #7 and is part of this release now.

**Comment by usergenic** [comment]
published koa-node-resolve@1.0.0-pre.3

**Pull request merged**
